.PHONY: all clean

CPPFLAGS+=
LDFLAGS+=-lm     # link to math library

TARGET=train test test_forward

all: $(TARGET)
# type make/make all to compile test_hmm
clean:
	$(RM) $(TARGET)   # type make clean to remove the compiled file
